// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50PZ-UufOf7xEtI8tfdv9_0N-KUbMWBY',
    appId: '1:985101924445:web:23d41468c318b259a2b5b4',
    messagingSenderId: '985101924445',
    projectId: 'webmd-bd3d0',
    authDomain: 'webmd-bd3d0.firebaseapp.com',
    storageBucket: 'webmd-bd3d0.appspot.com',
    measurementId: 'G-6GXQSBFNJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0CNP2zISDX-yVD7c9PcN5RtzBXu6fr0',
    appId: '1:985101924445:android:24216d8224370fe7a2b5b4',
    messagingSenderId: '985101924445',
    projectId: 'webmd-bd3d0',
    storageBucket: 'webmd-bd3d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKYmfUjTjhhbbkn1gX8t9zT6_Wx2Qquk',
    appId: '1:985101924445:ios:f0487ab35526d2b2a2b5b4',
    messagingSenderId: '985101924445',
    projectId: 'webmd-bd3d0',
    storageBucket: 'webmd-bd3d0.appspot.com',
    iosBundleId: 'com.example.flutter.testdrive.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgKYmfUjTjhhbbkn1gX8t9zT6_Wx2Qquk',
    appId: '1:985101924445:ios:3f320999636f40cca2b5b4',
    messagingSenderId: '985101924445',
    projectId: 'webmd-bd3d0',
    storageBucket: 'webmd-bd3d0.appspot.com',
    iosBundleId: 'com.example.flutter.testdrive.testDrive.RunnerTests',
  );
}
